name: Deploy HRMS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      PROJECT_NAME: "hrmdensaytest"
      GIT_REPO: "https://github.com/ghost-00007/hrmsdensay.git"
      PROJECT_FOLDER: "${{ env.PROJECT_NAME }}"
      WWW_PATH: "/var/www"
      NGINX_CONF_PATH: "/etc/nginx/sites-available/${{ env.PROJECT_NAME }}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clone or Pull Repository
        run: |
          if [ ! -d "${{ env.PROJECT_FOLDER }}/.git" ]; then
            echo "Cloning repository into ${PROJECT_FOLDER}..."
            git clone ${{ env.GIT_REPO }} ${{ env.PROJECT_FOLDER }}
          else
            echo "Repository already cloned. Pulling latest changes..."
            cd ${{ env.PROJECT_FOLDER }} && git pull
          fi

      - name: Copy to /var/www
        run: sudo cp -r ${{ env.PROJECT_FOLDER }} ${{ env.WWW_PATH }}/

      - name: Update Package List
        run: sudo apt update

      - name: Create Nginx Config
        run: |
          echo "
          server {
              listen 80;
              server_name localhost;
              root ${{ env.WWW_PATH }}/${{ env.PROJECT_NAME }};
              index index.html;

              location / {
                  try_files \$uri /index.html;
              }

              error_log /var/log/nginx/frontend_error.log;
              access_log /var/log/nginx/frontend_access.log;
          }" | sudo tee ${{ env.NGINX_CONF_PATH }}

