name: Deploy HRMS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      PROJECT_NAME: "hrmdensaytest"
      GIT_REPO: "https://github.com/ghost-00007/hrmsdensay.git"
      WWW_PATH: "/var/www"
      NGINX_CONF_PATH: "/etc/nginx/sites-available/${{ env.PROJECT_NAME }}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clone or Pull Repository
        run: |
          if [ ! -d "${PROJECT_NAME}/.git" ]; then
            echo "Cloning repository into ${PROJECT_NAME}..."
            git clone $GIT_REPO $PROJECT_NAME
          else
            echo "Repository already cloned. Pulling latest changes..."
            cd $PROJECT_NAME && git pull
          fi

      - name: Copy to /var/www
        run: sudo cp -r $PROJECT_NAME $WWW_PATH/

      - name: Update Package List
        run: sudo apt update

      - name: Create Nginx Config
        run: |
          echo "
          server {
              listen 80;
              server_name localhost;
              root $WWW_PATH/$PROJECT_NAME;
              index index.html;

              location / {
                  try_files \$uri /index.html;
              }

              error_log /var/log/nginx/frontend_error.log;
              access_log /var/log/nginx/frontend_access.log;
          }" | sudo tee $NGINX_CONF_PATH

      - name: Test Nginx Config
        run: sudo nginx -t

      - name: Restart Nginx
        run: sudo systemctl restart nginx
