name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    env:
      PROJECT_NAME: hrmdensaytest
      GIT_REPO: https://github.com/ghost-00007/hrmsdensay.git
      WWW_PATH: /var/www
      NGINX_CONF_PATH: /etc/nginx/sites-available/hrmdensaytest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Clone or update project repo
        run: |
          if [ ! -d "$PROJECT_NAME/.git" ]; then
            echo "Cloning repository into $PROJECT_NAME..."
            git clone $GIT_REPO $PROJECT_NAME
          else
            echo "Repository already cloned. Pulling latest changes..."
            cd $PROJECT_NAME && git pull
          fi

      - name: Copy files to /var/www
        run: |
          sudo cp -r $PROJECT_NAME $WWW_PATH/

      - name: Update package list
        run: |
          sudo apt update

      - name: Create Nginx config
        run: |
          echo '
          server {
              listen 80;
              server_name localhost;
              root $WWW_PATH/$PROJECT_NAME;
              index index.html;

              location / {
                  try_files \$uri /index.html;
              }

              error_log /var/log/nginx/frontend_error.log;
              access_log /var/log/nginx/frontend_access.log;
         
